### ISSUE TITLE
Changing table of models

### ISSUE THREAD

**Issue by SchollJ** [jayrobwilliams/RWmisc#3]
Is it possible to change the column labels to something other than 'model 1' etc? (Sorry I'm not familiar with LaTeX at all and it's also my first project with R..)

**Comment by jayrobwilliams** [comment]
Yes. The `...` argument at the end of `mcmcreg()` allows you to pass additional arguments to `texreg()`, which has an argument called `custom.model.names` that you can use to set more descriptive model names. For example, if you had two model objects, `mod1` and `mod2` with parameters `alpha` and `beta`, and you wanted to indicate the type of dependent variable used in each, you could do something like this:

```
mcmcreg(list(mod1, mod2), pars = c('alpha', 'beta'),
        custom.model.names = c('Binary Outcome', 'Count Outcome')
```

Take a look a the `texreg()` [documentation](https://www.rdocumentation.org/packages/texreg/versions/1.36.18/topics/texreg) for lots of other options to customize your tables.
