### ISSUE TITLE
upcoming sf 1.0-0 breaks RWmisc

### ISSUE THREAD

**Issue by edzer** [jayrobwilliams/RWmisc#7]
Please see https://github.com/r-spatial/sf/issues/1649

The prroblem I see is in the vignette, where in `st_coordinates(nc_points[farthest_ind,]`  the comma needs to be removed (because  `nc_points` is an `sfc` object).

`sf` has been submitted to CRAN.

**Comment by jayrobwilliams** [comment]
Thanks for the heads up; fixed in f60f9d056b212ba968aae1589219646fad8baa6c.
